#!/usr/bin/perl
@rocks = qw{ flintstone slate rubble };
print "quartz @rocks limestone\n";
print "Three rocks are: @rocks.\n";
print "There's nothing in the parens (@empty) here.\n";

@fred = qw(hello dolly);
$y = 2;
$x = "This is $fred[1]'s place";
print "\$x = $x\n";
$x = "This is $fred[$y-1]'s place";
print "\$x = $x\n";

