#!/usr/bin/perl
use strict;

$_ = "I saw Barney with Fred.";
print "$_\n";
s/(fred|barney)/\U$1/gi;
print "$_\n";
s/(fred|barney)/\L$1/gi;
print "$_\n";
s/(\w+) with (\w+)/\U$2\E with $1/i;
print "$_\n";
s/(fred|barney)/\u\L$1/ig;
print "$_\n";

